name: 'Autoroute'
description: 'Autoroute a given DSN file to SES with FreeRouting'
inputs:
  boards:
    description: 'Specctra SES output file'
    required: true
runs:
  using: 'docker'
  image: 'docker://nixos/nix'
  args:
    - '-c'
    - |
      for board in ${{ inputs.boards }};
      do
        echo Processing $board
        if [ -e ergogen/output/pcbs/${board}.ses ]; then
          echo Cleaning up ergogen/output/pcbs/${board}.ses
          rm -f ergogen/output/pcbs/${board}.ses
        fi
        nix-shell --argstr board ${board} shell.nix
      done