meta:
  engine: 4.1.0
  name: mr_useful
  version: 0.1
  ref: &kb_ref "v0.1 pre-release"
  author: ceoloide
  url: &kb_url github.com/ceoloide/mr_useful

units:
  # Key and keycap measures
  kx: u # spacing between key centers (X-axis)
  ky: u # spacing between key centers (Y-axis)
  kp: 19 # padding (default: 19)
  ks: 19 # spread (deafult: 19)
  kcow: 14 # key cutout hole width (cherry: 14, choc: 13.8)
  kcoh: 14 # key cutout hole height (cherry: 14, choc: 13.8)
  keycw: 18 # keycap width (cherry: 18, choc: 17.5)
  keych: 18 # keycap height (cherry: 18, choc: 16.5)
  led_pos_x: 0 # Led X position relative to the switch center
  led_pos_y: 4.75 # Led Y position relative to the switch center
  led_rotation: 0 # Led rotation
  vertical_underglow_shift: 0.5 kp # How much to shift underglow leds tied to keys
  diode_pos_x: 2.16 # Led X position relative to the switch center
  diode_pos_y: -6.0 # Led Y position relative to the switch center
  diode_rotation: 0 # Diode rotation
  switch_rotation: 180 # 0 = Hotswap south, led north

  # Physical measures
  screw_radius: 1.1 # M2 screws
  spacer_radius: 2.05 # M2 standoffs
  fillet_radius: 1
  pcb_tolerance: 0.5 # How much to expand the PCB on a single side
  frame_dimension: 4 # The size of the stacked acrylic frame

points:
  zones:
    arrows:
      anchor:
        shift: [60, -125]
      key:
        tags: 
          - key
      columns:
        left:
          key:
            column_net: C0
          rows:
            down:
              row_net: R0
              key:
                led_prev: LED_3
                led_next: LED_4
                underglow_prev: ULED_2
                underglow_next: ULED_3
        middle:
          key:
            column_net: C1
          rows:
            down:
              row_net: R0
              key:
                led_prev: LED_4
                led_next: LED_5
            up:
              row_net: R1
              key:
                led_prev: LED_5
                led_next: LED_6
                underglow_prev: ULED_1
                underglow_next: ULED_2
        right:
          key:
            column_net: C2
          rows:
            down:
              row_net: R0
              key:
                led_prev: LED_9
                led_next: LED_10
                underglow_prev: LED_10
                underglow_next: ULED_1
    navigation:
      key:
        tags: 
          - key
      anchor:
        ref: arrows_middle_up
        shift: [-1 u, 2 u]
      columns:
        first:
          key:
            column_net: C0
          rows:
            top.key:
              led_prev: LED_1
              led_next: LED_2
            bottom.key:
              led_prev: LED_2
              led_next: LED_3
              underglow_prev: ULED_3
              underglow_next: ULED_4
        second:
          key:
            column_net: C1
          rows:
            top.key:
              led_prev: LED
              led_next: LED_1
            bottom.key:
              led_prev: LED_6
              led_next: LED_7
        third:
          key:
            column_net: C2
          rows:
            top.key:
              led_prev: LED_7
              led_next: LED_8
            bottom.key:
              led_prev: LED_8
              led_next: LED_9
              underglow_prev: ULED_4
              underglow_next: ULED_5
      rows:
        bottom:
          row_net: R3
        top:
          row_net: R4

    # The following are helpers for component
    # placement
    top_left_screw: &screw
      anchor:
        ref: navigation_first_top
        shift: [-0.5 ks - (pcb_tolerance + frame_dimension),0.5 kp + (pcb_tolerance + frame_dimension)]
      key:
        tags:
          - screw
        height: 0
        width: 0
    top_right_screw:
      <<: *screw
      anchor:
        ref: navigation_third_top
        shift: [0.5 ks + (pcb_tolerance + frame_dimension),0.5 kp + (pcb_tolerance + frame_dimension)]
    mid_left_screw:
      <<: *screw
      anchor:
        ref: arrows_middle_up
        shift: [-1.5 ks - (pcb_tolerance + frame_dimension),1 kp]
    mid_right_screw:
      <<: *screw
      anchor:
        ref: arrows_middle_up
        shift: [1.5 ks + (pcb_tolerance + frame_dimension),1 kp]
    bottom_left_screw:
      <<: *screw
      anchor:
        ref: arrows_left_down
        shift: [-0.5 ks - (pcb_tolerance + frame_dimension),-0.5 kp - (pcb_tolerance + frame_dimension)]
    bottom_right_screw:
      <<: *screw
      anchor:
        ref: arrows_right_down
        shift: [0.5 ks + (pcb_tolerance + frame_dimension),-0.5 kp - (pcb_tolerance + frame_dimension)]

outlines:
  debug_points:
    - what: rectangle
      where: true
      size: [6,0.01]
    - what: rectangle
      where: true
      size: [0.01,4]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [3,0]
    - what: circle
      where: true
      radius: 0.4
      adjust:
        shift: [0,2]
    - what: rectangle
      where: [key]
      size: [kx, ky]
      operation: stack
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]
      operation: stack
    - what: circle
      where: [screw]
      radius: 2
      operation: stack

  _switch_cutouts:
    - what: rectangle
      where: [key]
      size: [kcow, kcoh]

  _screws:
    - what: circle
      where: [screw]
      radius: screw_radius

  _spacers:
    - what: circle
      where: [screw]
      radius: spacer_radius

  _base:
    - what: rectangle
      where: arrows_middle_up
      size: [3 ks, 5 kp]
      adjust:
        shift: [0, kp]
  
  _xiao_footprint:
    - what: rectangle
      where: navigation_second_top
      size: [17.8, 21] # XIAO SAMD21 PCB size
      adjust:
        shift: [0, 0]
    - what: rectangle
      where: navigation_second_top
      size: [9, 7.35] # USB-C port
      adjust:
        shift: [0, 8.2465]

  _xiao_footprint_tolerance:
    - what: outline
      name: _xiao_footprint
      expand: pcb_tolerance * 2

  pcb:
    - what: outline
      name: _base
      fillet: fillet_radius

  _pcb_tolerance:
    - what: outline
      name: pcb
      expand: pcb_tolerance * 2

  front_plate:
    - what: outline
      name: _base
      expand: frame_dimension * 2
      joints: 1
      fillet: fillet_radius * 2
    - what: outline
      name: _switch_cutouts
      operation: subtract
    - what: outline
      name: _screws
      operation: subtract

  back_plate:
    - what: outline
      name: front_plate
    - what: outline
      name: _base
      operation: add

  spacer_plate_top:
    - what: outline
      name: front_plate
    - what: outline
      name: _pcb_tolerance
      operation: subtract
    - what: outline
      name: _spacers
      operation: subtract

  spacer_plate_bottom:
    - what: outline
      name: front_plate
    - what: outline
      name: _pcb_tolerance
      operation: subtract
    - what: outline
      name: _spacers
      operation: subtract
    - what: outline
      name: _xiao_footprint_tolerance
      operation: subtract
    - what: rectangle
      where: navigation_second_top
      size: [13, 20] # XIAO SAMD21 PCB size
      adjust:
        shift: [0, 8]
      operation: subtract

  preview:
    - what: outline
      name: debug_points
    - what: rectangle
      where: [key]
      size: [keycw, keych]
      operation: stack
    - what: outline
      name: _switch_cutouts
      operation: stack
    - what: outline
      name: _screws
      operation: stack
    - what: outline
      name: pcb
      operation: stack
    - what: outline
      name: spacer_plate_top
      operation: stack
    - what: outline
      name: spacer_plate_bottom
      operation: stack
    - what: outline
      name: _xiao_footprint
      operation: stack
    - what: rectangle
      where: navigation_second_top
      size: [9, 7.35] # XIAO USB-C
      adjust:
        shift: [0, 8.2465]
      operation: stack

pcbs:
  back_plate:
    template: kicad8
    outlines:
      main:
        outline: back_plate
  front_plate:
    template: kicad8
    outlines:
      main:
        outline: front_plate
    footprints:
      logo:
        what: logo_mr_useful
        where: arrows_middle_up
        params:
          text_line_1: *kb_url
          text_line_2: *kb_ref
        adjust:
          shift: [0,1 ks]
  spacer_plate_bottom:
    template: kicad8
    outlines:
      main:
        outline: spacer_plate_bottom
  spacer_plate_top:
    template: kicad8
    outlines:
      main:
        outline: spacer_plate_top
  mr_useful:
    template: kicad8
    outlines:
      main:
        outline: pcb
    footprints:
      key_switches:
        what: ceoloide/switch_mx
        where: [key]
        params:
          reversible: false
          hotswap: false
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: switch_rotation
      
      per_key_leds:
        what: ceoloide/led_sk6812mini-e
        where: [key]
        params:
          P1: VCC
          P2: "{{key.led_next}}" #DOUT
          P3: GND
          P4: "{{key.led_prev}}" #DIN
          reversible: false
          reverse_mount: true
          include_courtyard: false
          include_keepout: false
        adjust:
          shift: [led_pos_x, led_pos_y]
          rotate: led_rotation
      
      underglow_leds:
        what: ceoloide/led_sk6812mini-e
        where:
          - navigation_first_bottom
          - navigation_third_bottom
          - arrows_middle_up
          - arrows_left_down
          - arrows_right_down
        params:
          P1: VCC
          P2: "{{key.underglow_next}}" #DOUT
          P3: GND
          P4: "{{key.underglow_prev}}" #DIN
          reversible: false
          reverse_mount: false
          include_courtyard: false
          include_keepout: false
        adjust:
          shift: [0, vertical_underglow_shift]
          rotate: led_rotation + 180

      diodes:
        what: ceoloide/diode_tht_sod123
        where: [key]
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          include_tht: false
          reversible: false
          side: B
        adjust:
          shift: [diode_pos_x, diode_pos_y]
          rotate: diode_rotation

      mcu:
        what: seeedstudio_xiao
        where: navigation_second_top
        params:
          side: B
          flip: false  # MCU faces away from PCB
          P3: LED
          P4: C0
          P5: C1
          P6: C3
          P7: R3
          P8: R2
          P9: R1
          P10: R0
          RAW3V3: VCC
      
      logo:
        what: logo_mr_useful
        where: arrows_middle_up
        params:
          text_line_1: *kb_url
          text_line_2: *kb_ref
          side: F
        adjust:
          shift: [0,1 ks]
      
      jlcpcb_order_number_text:
        what: ceoloide/utility_text
        where: arrows_middle_up
        params:
          text: JLCJLCJLCJLC
          side: B
          mirrored: true
        adjust:
          shift: [0,1 ks]