on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/*.yaml'
      - '.github/actions/*/action.yaml'
      - 'ergogen/footprints/*.js'
      - 'ergogen/config.yaml'
      - 'kibot/*'
      - 'freerouting/*'
      - 'package.json'
      - '*.nix'

name: Build
jobs:
  board:
    runs-on: ubuntu-latest
    name: Generate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Docker Cache
        uses: ScribeMD/docker-cache@0.3.7
        with:
          key: docker-${{ runner.os }}
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Generate unrouted PCBs with Ergogen (definition in package.json)
        run: npm run build
      - name: Run KiBot to generate images, gerbers for the plate files
        uses: ./.github/actions/kibot
        with:
          boards: back_plate front_plate spacer_plate_bottom spacer_plate_top
          config: default
      - name: Run KiBot to generate images, gerbers for the unrouted board
        uses: ./.github/actions/kibot
        with:
          boards: mr_useful
          config: default
      - name: Export DSN file for Freerouting
        uses: ./.github/actions/export-dsn
        with:
          boards: mr_useful
      - name: Autoroute PCB
        uses: ./.github/actions/autoroute
        with:
          boards: mr_useful
      - name: Import SES
        uses: ./.github/actions/import-ses
        with:
          boards: mr_useful
      - name: Run KiBot to generate images, gerbers for the autorouted board
        uses: ./.github/actions/kibot
        with:
          boards: mr_useful_autorouted
          config: boards
      - name: Persist output
        uses: actions/upload-artifact@v4
        with:
          name: mr_useful
          path: ergogen/output
